### ISSUE TITLE
Colours don't convert into index 0 unless it's through Sprite sheet importing

### ISSUE THREAD

**Issue by VAdaPEGA** [kirjavascript/Flex2#39]
When using "Import Over Sprite", index 0 from the palette isn't being considered as the transparency colour at all, making it impossible to use an opaque image for any small changes. 
This isn't the case for the "Import spritesheet" function, which automatically assumes the background colour as transparent.
This can get really annoying for updating any existing sprites when you mainly use a tool that doesn't support transparency (such as MSPaint) and have to rely on a separate program to remove the background colour.

Sprite example used for importing :
![image](https://user-images.githubusercontent.com/50675500/124360131-6074c500-dc28-11eb-92b5-40b586995b2f.png)

Expected Result :
![image](https://user-images.githubusercontent.com/50675500/124360092-2277a100-dc28-11eb-81ed-052e9a6e0f5c.png)

Actual Result :
![image](https://user-images.githubusercontent.com/50675500/124360107-36bb9e00-dc28-11eb-9e1f-1b915f5e8ec7.png)

**Comment by kirjavascript** [comment]
yeah this is intentional. using pixel 0 works well for a spritesheet because it usually contains multiple sprites and that pixel will not be in range of sprites to affect them. 

with a single sprite that pixel is part of the sprite - there are usecases that cause issues (like importing an image of a single colour and have the tiles be that colour, rather than transparency)

it would still be nice to allow users to have this transparency detection too though, so, I'll try and have a configuration option for it in the next version

**Comment by flamewing** [comment]
Note that VAdaPEGA mentioned "index 0 of the palette", not pixel 0. I would assume that he is importing a palleted image using the same palette that is used in-game.

**Comment by kirjavascript** [comment]
aha, my mistake. yeah this is a bug then and I'll get it fixed

**Comment by kirjavascript** [comment]
fixed in 1.3.0
